services:
  - type: static
    name: sleeper-archive-hangman
    env: static
    rootDir: SleeperArchive
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
