// EVE Online Static Data Export (SDE) Compatible Database
// Schema: invCategories -> invGroups -> invTypes
// Source: https://developers.eveonline.com/static-data/
// Format matches official SDE JSON/YAML structure

// Category IDs from invCategories (official SDE)
const Categories = {
    4: { name: "Material", icon: "fa-cube" },
    6: { name: "Ship", icon: "fa-rocket" },
    7: { name: "Module", icon: "fa-microchip" },
    8: { name: "Charge", icon: "fa-bullseye" },
    9: { name: "Blueprint", icon: "fa-scroll" },
    16: { name: "Skill", icon: "fa-graduation-cap" },
    20: { name: "Implant", icon: "fa-brain" },
    22: { name: "Deployable", icon: "fa-box" },
    24: { name: "Starbase", icon: "fa-satellite" },
    30: { name: "Subsystem", icon: "fa-puzzle-piece" },
    32: { name: "Asteroid", icon: "fa-meteor" },
    34: { name: "Apparel", icon: "fa-tshirt" },
    35: { name: "Accessory", icon: "fa-headphones" },
    39: { name: "Commodity", icon: "fa-boxes" },
    40: { name: "Drone", icon: "fa-fighter-jet" },
    43: { name: "Planetary Industry", icon: "fa-globe" }
};

// Group IDs from invGroups (official SDE)
const Groups = {
    // Materials (Category 4)
    18: { name: "Mineral", categoryID: 4 },
    427: { name: "Moon Materials", categoryID: 4 },
    423: { name: "Ice Product", categoryID: 4 },
    754: { name: "Salvaged Materials", categoryID: 4 },
    1136: { name: "Hybrid Polymers", categoryID: 4 },
    
    // Ships (Category 6)
    25: { name: "Frigate", categoryID: 6 },
    26: { name: "Cruiser", categoryID: 6 },
    27: { name: "Battleship", categoryID: 6 },
    28: { name: "Industrial", categoryID: 6 },
    30: { name: "Titan", categoryID: 6 },
    31: { name: "Shuttle", categoryID: 6 },
    324: { name: "Assault Frigate", categoryID: 6 },
    358: { name: "Heavy Assault Cruiser", categoryID: 6 },
    380: { name: "Deep Space Transport", categoryID: 6 },
    381: { name: "Elite Battleship", categoryID: 6 },
    384: { name: "Blockade Runner", categoryID: 6 },
    419: { name: "Combat Battlecruiser", categoryID: 6 },
    420: { name: "Destroyer", categoryID: 6 },
    463: { name: "Strategic Cruiser", categoryID: 6 },
    485: { name: "Dreadnought", categoryID: 6 },
    547: { name: "Freighter", categoryID: 6 },
    659: { name: "Command Ship", categoryID: 6 },
    883: { name: "Carrier", categoryID: 6 },
    894: { name: "Supercarrier", categoryID: 6 },
    898: { name: "Disruption Battlecruiser", categoryID: 6 },
    900: { name: "Exhumer", categoryID: 6 },
    902: { name: "Electronic Attack Ship", categoryID: 6 },
    906: { name: "Heavy Interdiction Cruiser", categoryID: 6 },
    941: { name: "Jump Freighter", categoryID: 6 },
    963: { name: "Logistics", categoryID: 6 },
    1023: { name: "Interceptor", categoryID: 6 },
    1201: { name: "Logistics Frigate", categoryID: 6 },
    1202: { name: "Command Destroyer", categoryID: 6 },
    1305: { name: "Tactical Destroyer", categoryID: 6 },
    1527: { name: "Force Auxiliary", categoryID: 6 },
    1534: { name: "Command Battlecruiser", categoryID: 6 },
    1538: { name: "Flag Cruiser", categoryID: 6 },
    1972: { name: "Corvette", categoryID: 6 },
    
    // Modules (Category 7)
    53: { name: "Hybrid Weapon", categoryID: 7 },
    54: { name: "Laser Turret", categoryID: 7 },
    55: { name: "Projectile Weapon", categoryID: 7 },
    74: { name: "Missile Launcher", categoryID: 7 },
    76: { name: "Shield Extender", categoryID: 7 },
    77: { name: "Shield Hardener", categoryID: 7 },
    78: { name: "Shield Recharger", categoryID: 7 },
    38: { name: "Shield Booster", categoryID: 7 },
    39: { name: "Shield Amplifier", categoryID: 7 },
    40: { name: "Shield Repair Unit", categoryID: 7 },
    41: { name: "Shield Power Relay", categoryID: 7 },
    46: { name: "Propulsion Module", categoryID: 7 },
    47: { name: "Electronic Counter Measure", categoryID: 7 },
    48: { name: "ECM Stabilizer", categoryID: 7 },
    49: { name: "Sensor Backup Array", categoryID: 7 },
    50: { name: "Heat Sink", categoryID: 7 },
    52: { name: "Stasis Web", categoryID: 7 },
    56: { name: "Capacitor Battery", categoryID: 7 },
    57: { name: "Armor Repair Unit", categoryID: 7 },
    58: { name: "Hull Repair Unit", categoryID: 7 },
    59: { name: "Armor Reinforcer", categoryID: 7 },
    60: { name: "Remote Capacitor Transmitter", categoryID: 7 },
    61: { name: "Energy Nosferatu", categoryID: 7 },
    62: { name: "Energy Neutralizer", categoryID: 7 },
    67: { name: "Smart Bomb", categoryID: 7 },
    68: { name: "Hull Upgrades", categoryID: 7 },
    71: { name: "Weapon Upgrade", categoryID: 7 },
    72: { name: "Mining Laser", categoryID: 7 },
    74: { name: "Missile Launcher", categoryID: 7 },
    76: { name: "Shield Extender", categoryID: 7 },
    325: { name: "Armor Coating", categoryID: 7 },
    329: { name: "Armor Hardener", categoryID: 7 },
    330: { name: "Armor Plates", categoryID: 7 },
    339: { name: "Warp Scrambler", categoryID: 7 },
    340: { name: "Warp Disruptor", categoryID: 7 },
    371: { name: "Energy Transfer Array", categoryID: 7 },
    372: { name: "Remote Armor Repairer", categoryID: 7 },
    373: { name: "Remote Hull Repairer", categoryID: 7 },
    379: { name: "Shield Hardening Bot", categoryID: 7 },
    407: { name: "Damage Control", categoryID: 7 },
    437: { name: "Drone Upgrade", categoryID: 7 },
    464: { name: "Capacitor Booster", categoryID: 7 },
    482: { name: "Cloaking Device", categoryID: 7 },
    487: { name: "Tractor Beam", categoryID: 7 },
    515: { name: "Automated Targeting System", categoryID: 7 },
    514: { name: "Survey Probe Launcher", categoryID: 7 },
    507: { name: "Siege Module", categoryID: 7 },
    508: { name: "Triage Module", categoryID: 7 },
    511: { name: "Industral Core", categoryID: 7 },
    595: { name: "Tracking Enhancer", categoryID: 7 },
    596: { name: "Gang Coordinator", categoryID: 7 },
    597: { name: "Data Miner", categoryID: 7 },
    629: { name: "Mining Upgrade", categoryID: 7 },
    644: { name: "Frequency Mining Laser", categoryID: 7 },
    650: { name: "Projectile Ammo", categoryID: 7 },
    661: { name: "Hybrid Charge", categoryID: 7 },
    772: { name: "Tracking Computer", categoryID: 7 },
    773: { name: "Tracking Disruptor", categoryID: 7 },
    774: { name: "Sensor Booster", categoryID: 7 },
    776: { name: "Sensor Dampener", categoryID: 7 },
    909: { name: "Target Painter", categoryID: 7 },
    1150: { name: "Missile Guidance Computer", categoryID: 7 },
    1153: { name: "Missile Guidance Enhancer", categoryID: 7 },
    1284: { name: "Ancillary Shield Booster", categoryID: 7 },
    1533: { name: "Rapture Burst Jammer", categoryID: 7 },
    1672: { name: "Siege Module II", categoryID: 7 },
    1690: { name: "Entosis Link", categoryID: 7 },
    1968: { name: "Burst Jammer", categoryID: 7 },
    
    // Charges (Category 8)
    85: { name: "Projectile Ammo", categoryID: 8 },
    86: { name: "Hybrid Charge", categoryID: 8 },
    89: { name: "Frequency Crystal", categoryID: 8 },
    90: { name: "Rocket", categoryID: 8 },
    91: { name: "Capacitor Booster Charge", categoryID: 8 },
    92: { name: "Nanite Repair Paste", categoryID: 8 },
    93: { name: "Light Missile", categoryID: 8 },
    94: { name: "Heavy Missile", categoryID: 8 },
    95: { name: "Torpedo", categoryID: 8 },
    96: { name: "Bomb", categoryID: 8 },
    97: { name: "Mine", categoryID: 8 },
    98: { name: "Cruise Missile", categoryID: 8 },
    384: { name: "Defender Missile", categoryID: 8 },
    385: { name: "Citadel Torpedo", categoryID: 8 },
    386: { name: "Bomb ECM", categoryID: 8 },
    387: { name: "Bomb Energy", categoryID: 8 },
    476: { name: "Heavy Assault Missile", categoryID: 8 },
    657: { name: "Citadel Cruise Missile", categoryID: 8 },
    648: { name: "XL Torpedo", categoryID: 8 },
    745: { name: "Guided Bomb", categoryID: 8 },
    756: { name: "Structure Torpedo", categoryID: 8 },
    1261: { name: "Rapid Heavy Missile", categoryID: 8 },
    1547: { name: "Structure Guided Bomb", categoryID: 8 },
    1549: { name: "Structure Anti-Capital Missile", categoryID: 8 },
    1551: { name: "Structure Anti-Subcapital Missile", categoryID: 8 },
    1760: { name: "Missile Guidance Script", categoryID: 8 },
    1793: { name: "Structure Area Denial Missile", categoryID: 8 },
    
    // Drones (Category 40)
    97: { name: "Light Scout Drone", categoryID: 40 },
    100: { name: "Mining Drone", categoryID: 40 },
    101: { name: "Logistic Drone", categoryID: 40 },
    299: { name: "Medium Scout Drone", categoryID: 40 },
    301: { name: "Heavy Attack Drone", categoryID: 40 },
    343: { name: "Sentry Drone", categoryID: 40 },
    544: { name: "Fighter Drone", categoryID: 40 },
    549: { name: "Fighter Bomber", categoryID: 40 },
    1001: { name: "Heavy Fighter", categoryID: 40 },
    1002: { name: "Light Fighter", categoryID: 40 },
    1003: { name: "Support Fighter", categoryID: 40 },
    1159: { name: "Structure Repair Drone", categoryID: 40 },
    1272: { name: "Electronic Warfare Drone", categoryID: 40 },
    
    // Commodities/Trade Goods (Category 39)
    1033: { name: "General", categoryID: 39 },
    1041: { name: "Planetary Resources", categoryID: 39 },
    1048: { name: "Artifacts and Prototypes", categoryID: 39 },
    1204: { name: "Special Edition Assets", categoryID: 39 },
    1708: { name: "Proof of Discovery", categoryID: 39 }
};

// Item Types from invTypes (official SDE structure)
// Format: { typeID: { name, groupID, categoryID, marketGroupID, volume, mass, ... } }
const Types = {
    // Materials & Resources
    materials: {
        name: "Materials",
        icon: "fa-cube",
        items: [
            // Minerals
            { id: 34, name: "Tritanium" },
            { id: 35, name: "Pyerite" },
            { id: 36, name: "Mexallon" },
            { id: 37, name: "Isogen" },
            { id: 38, name: "Nocxium" },
            { id: 39, name: "Zydrine" },
            { id: 40, name: "Megacyte" },
            { id: 11399, name: "Morphite" },
            // Moon Materials
            { id: 16633, name: "Atmospheric Gases" },
            { id: 16634, name: "Cadmium" },
            { id: 16635, name: "Caesium" },
            { id: 16636, name: "Chromium" },
            { id: 16637, name: "Cobalt" },
            { id: 16638, name: "Dysprosium" },
            { id: 16639, name: "Evaporite Deposits" },
            { id: 16640, name: "Hafnium" },
            { id: 16641, name: "Hydrocarbons" },
            { id: 16642, name: "Mercury" },
            { id: 16643, name: "Neodymium" },
            { id: 16644, name: "Platinum" },
            { id: 16645, name: "Promethium" },
            { id: 16646, name: "Scandium" },
            { id: 16647, name: "Silicates" },
            { id: 16648, name: "Technetium" },
            { id: 16649, name: "Thulium" },
            { id: 16650, name: "Titanium" },
            { id: 16651, name: "Tungsten" },
            { id: 16652, name: "Vanadium" },
            // Ice Products
            { id: 16274, name: "Helium Isotopes" },
            { id: 16272, name: "Hydrogen Isotopes" },
            { id: 16273, name: "Nitrogen Isotopes" },
            { id: 16275, name: "Oxygen Isotopes" },
            { id: 17887, name: "Heavy Water" },
            { id: 17888, name: "Liquid Ozone" },
            { id: 17889, name: "Strontium Clathrates" },
            // Salvage
            { id: 25588, name: "Armor Plates" },
            { id: 25605, name: "Capacitor Console" },
            { id: 25600, name: "Charred Micro Circuit" },
            { id: 25596, name: "Conductive Polymer" },
            { id: 25592, name: "Contaminated Nanite Compound" },
            { id: 25590, name: "Damaged Artificial Neural Network" },
            { id: 25604, name: "Defective Current Pump" },
            { id: 25601, name: "Fried Interface Circuit" },
            { id: 25595, name: "Malfunctioning Shield Emitter" },
            { id: 25597, name: "Melted Capacitor Console" },
            { id: 25603, name: "Scorched Telemetry Processor" },
            { id: 25589, name: "Smashed Trigger Unit" },
            { id: 25602, name: "Tangled Power Conduit" },
            { id: 25593, name: "Thruster Console" },
            { id: 25591, name: "Tripped Power Circuit" },
            { id: 25594, name: "Ward Console" },
            { id: 25624, name: "Intact Armor Plates" },
            { id: 25625, name: "Intact Shield Emitter" },
            { id: 25626, name: "Intact Nanite Compound" },
            { id: 25627, name: "Intact Neural Network" },
            { id: 25628, name: "Intact Power Circuit" },
            { id: 25629, name: "Intact Power Conduit" },
        ]
    },
    
    // Ships - Frigates
    frigates: {
        name: "Frigates",
        icon: "fa-rocket",
        items: [
            // Tech 1 Frigates
            { id: 587, name: "Rifter" },
            { id: 586, name: "Condor" },
            { id: 583, name: "Executioner" },
            { id: 585, name: "Atron" },
            { id: 582, name: "Bantam" },
            { id: 592, name: "Navitas" },
            { id: 590, name: "Burst" },
            { id: 588, name: "Slasher" },
            { id: 591, name: "Vigil" },
            { id: 594, name: "Merlin" },
            { id: 595, name: "Incursus" },
            { id: 597, name: "Imicus" },
            { id: 598, name: "Heron" },
            { id: 599, name: "Kestrel" },
            { id: 600, name: "Probe" },
            { id: 11134, name: "Crucifier" },
            { id: 11186, name: "Maulus" },
            { id: 11192, name: "Griffin" },
            { id: 11196, name: "Tristan" },
            { id: 11202, name: "Breacher" },
            { id: 11208, name: "Inquisitor" },
            { id: 11210, name: "Tormentor" },
            { id: 11218, name: "Punisher" },
            { id: 11228, name: "Vexor" },
            { id: 11238, name: "Incursus" },
            // Navy Frigates
            { id: 11400, name: "Imperial Navy Slicer" },
            { id: 11401, name: "Caldari Navy Hookbill" },
            { id: 11402, name: "Federation Navy Comet" },
            { id: 11403, name: "Republic Fleet Firetail" },
            // Interceptors
            { id: 11176, name: "Claw" },
            { id: 11178, name: "Stiletto" },
            { id: 11182, name: "Crow" },
            { id: 11184, name: "Raptor" },
            { id: 11188, name: "Taranis" },
            { id: 11190, name: "Ares" },
            { id: 11224, name: "Malediction" },
            { id: 11226, name: "Crusader" },
            // Covert Ops
            { id: 11172, name: "Cheetah" },
            { id: 11174, name: "Anathema" },
            { id: 11194, name: "Helios" },
            { id: 11198, name: "Buzzard" },
            // Assault Frigates
            { id: 11369, name: "Wolf" },
            { id: 11371, name: "Jaguar" },
            { id: 11373, name: "Harpy" },
            { id: 11375, name: "Hawk" },
            { id: 11377, name: "Enyo" },
            { id: 11379, name: "Ishkur" },
            { id: 11381, name: "Retribution" },
            { id: 11383, name: "Vengeance" },
            // Electronic Attack
            { id: 11387, name: "Kitsune" },
            { id: 11393, name: "Keres" },
            { id: 11395, name: "Hyena" },
            { id: 11397, name: "Sentinel" },
            // Logistics Frigates
            { id: 37457, name: "Deacon" },
            { id: 37458, name: "Scalpel" },
            { id: 37459, name: "Kirin" },
            { id: 37460, name: "Thalia" },
        ]
    },
    
    // Ships - Destroyers
    destroyers: {
        name: "Destroyers",
        icon: "fa-rocket",
        items: [
            // Tech 1
            { id: 16236, name: "Catalyst" },
            { id: 16238, name: "Coercer" },
            { id: 16240, name: "Cormorant" },
            { id: 16242, name: "Thrasher" },
            // Interdictors
            { id: 22456, name: "Eris" },
            { id: 22460, name: "Heretic" },
            { id: 22464, name: "Flycatcher" },
            { id: 22468, name: "Sabre" },
            // Command Destroyers
            { id: 37482, name: "Bifrost" },
            { id: 37483, name: "Pontifex" },
            { id: 37484, name: "Stork" },
            { id: 37485, name: "Magus" },
            // Tactical Destroyers
            { id: 34317, name: "Confessor" },
            { id: 35683, name: "Svipul" },
            { id: 37450, name: "Jackdaw" },
            { id: 37452, name: "Hecate" },
        ]
    },
    
    // Ships - Cruisers
    cruisers: {
        name: "Cruisers",
        icon: "fa-rocket",
        items: [
            // Tech 1
            { id: 620, name: "Stabber" },
            { id: 622, name: "Moa" },
            { id: 623, name: "Maller" },
            { id: 624, name: "Vexor" },
            { id: 625, name: "Thorax" },
            { id: 626, name: "Rupture" },
            { id: 627, name: "Caracal" },
            { id: 628, name: "Omen" },
            { id: 629, name: "Arbitrator" },
            { id: 630, name: "Exequror" },
            { id: 631, name: "Bellicose" },
            { id: 632, name: "Blackbird" },
            { id: 633, name: "Augoror" },
            { id: 634, name: "Vexor Navy Issue" },
            { id: 11011, name: "Moa" },
            { id: 11012, name: "Maller" },
            { id: 11013, name: "Stabber" },
            { id: 11014, name: "Thorax" },
            // Navy Cruisers
            { id: 11957, name: "Augoror Navy Issue" },
            { id: 11959, name: "Omen Navy Issue" },
            { id: 11961, name: "Caracal Navy Issue" },
            { id: 11963, name: "Stabber Fleet Issue" },
            { id: 11965, name: "Vexor Navy Issue" },
            { id: 11985, name: "Exequror Navy Issue" },
            { id: 11987, name: "Osprey Navy Issue" },
            { id: 11989, name: "Scythe Fleet Issue" },
            // Recon Ships
            { id: 11969, name: "Rook" },
            { id: 11971, name: "Falcon" },
            { id: 11973, name: "Arazu" },
            { id: 11975, name: "Lachesis" },
            { id: 11977, name: "Curse" },
            { id: 11979, name: "Pilgrim" },
            { id: 11981, name: "Huginn" },
            { id: 11983, name: "Rapier" },
            // Heavy Assault Cruisers
            { id: 12011, name: "Vagabond" },
            { id: 12013, name: "Cerberus" },
            { id: 12015, name: "Sacrilege" },
            { id: 12017, name: "Deimos" },
            { id: 12019, name: "Zealot" },
            { id: 12021, name: "Muninn" },
            { id: 12023, name: "Eagle" },
            { id: 12025, name: "Ishtar" },
            { id: 12037, name: "Vagabond" },
            { id: 12039, name: "Cerberus" },
            { id: 12041, name: "Sacrilege" },
            { id: 12043, name: "Deimos" },
            // Heavy Interdiction Cruisers
            { id: 12049, name: "Broadsword" },
            { id: 12052, name: "Onyx" },
            { id: 12054, name: "Devoter" },
            { id: 12056, name: "Phobos" },
            // Logistics Cruisers
            { id: 11995, name: "Basilisk" },
            { id: 11999, name: "Guardian" },
            { id: 12003, name: "Oneiros" },
            { id: 12005, name: "Scimitar" },
            // Strategic Cruisers (T3C)
            { id: 29984, name: "Proteus" },
            { id: 29986, name: "Legion" },
            { id: 29988, name: "Tengu" },
            { id: 29990, name: "Loki" },
        ]
    },
    
    // Ships - Battlecruisers
    battlecruisers: {
        name: "Battlecruisers",
        icon: "fa-rocket",
        items: [
            // Tech 1
            { id: 24696, name: "Hurricane" },
            { id: 24694, name: "Ferox" },
            { id: 24698, name: "Brutix" },
            { id: 24700, name: "Prophecy" },
            { id: 24688, name: "Drake" },
            { id: 24690, name: "Myrmidon" },
            { id: 24692, name: "Harbinger" },
            { id: 24702, name: "Cyclone" },
            // Navy Battlecruisers
            { id: 33153, name: "Brutix Navy Issue" },
            { id: 33155, name: "Drake Navy Issue" },
            { id: 33157, name: "Harbinger Navy Issue" },
            { id: 33159, name: "Hurricane Fleet Issue" },
            // Command Ships
            { id: 22474, name: "Damnation" },
            { id: 22476, name: "Claymore" },
            { id: 22478, name: "Astarte" },
            { id: 22480, name: "Nighthawk" },
            { id: 22482, name: "Vulture" },
            { id: 22484, name: "Absolution" },
            { id: 22486, name: "Sleipnir" },
            { id: 22488, name: "Eos" },
        ]
    },
    
    // Ships - Battleships
    battleships: {
        name: "Battleships",
        icon: "fa-rocket",
        items: [
            // Tech 1
            { id: 642, name: "Raven" },
            { id: 643, name: "Apocalypse" },
            { id: 644, name: "Megathron" },
            { id: 645, name: "Dominix" },
            { id: 638, name: "Tempest" },
            { id: 639, name: "Scorpion" },
            { id: 640, name: "Armageddon" },
            { id: 641, name: "Typhoon" },
            { id: 552, name: "Hyperion" },
            { id: 634, name: "Abaddon" },
            { id: 635, name: "Rokh" },
            { id: 636, name: "Maelstrom" },
            { id: 64069, name: "Praxis" },
            // Navy Battleships
            { id: 17636, name: "Raven Navy Issue" },
            { id: 17726, name: "Apocalypse Navy Issue" },
            { id: 17728, name: "Megathron Navy Issue" },
            { id: 17730, name: "Dominix Navy Issue" },
            { id: 17732, name: "Tempest Fleet Issue" },
            { id: 17734, name: "Scorpion Navy Issue" },
            { id: 17736, name: "Armageddon Navy Issue" },
            { id: 17738, name: "Typhoon Fleet Issue" },
            // Black Ops
            { id: 22446, name: "Widow" },
            { id: 22448, name: "Redeemer" },
            { id: 22450, name: "Sin" },
            { id: 22452, name: "Panther" },
            // Marauders
            { id: 28661, name: "Paladin" },
            { id: 28659, name: "Golem" },
            { id: 28657, name: "Kronos" },
            { id: 28665, name: "Vargur" },
        ]
    },
    
    // Ships - Industrial & Transport
    industrials: {
        name: "Industrial Ships",
        icon: "fa-truck",
        items: [
            // Tech 1 Industrials
            { id: 648, name: "Badger" },
            { id: 649, name: "Tayra" },
            { id: 650, name: "Nereus" },
            { id: 651, name: "Kryos" },
            { id: 652, name: "Epithal" },
            { id: 653, name: "Miasmos" },
            { id: 654, name: "Iteron Mark V" },
            { id: 656, name: "Mammoth" },
            { id: 657, name: "Wreathe" },
            { id: 658, name: "Sigil" },
            { id: 660, name: "Bestower" },
            { id: 670, name: "Badger Mark II" },
            { id: 685, name: "Iteron Mark IV" },
            // Deep Space Transports
            { id: 12729, name: "Occator" },
            { id: 12731, name: "Mastodon" },
            { id: 12735, name: "Bustard" },
            { id: 12743, name: "Impel" },
            // Blockade Runners
            { id: 12745, name: "Viator" },
            { id: 12747, name: "Prorator" },
            { id: 12753, name: "Crane" },
            { id: 12755, name: "Prowler" },
            // Freighters
            { id: 661, name: "Providence" },
            { id: 662, name: "Charon" },
            { id: 663, name: "Obelisk" },
            { id: 665, name: "Fenrir" },
            // Jump Freighters
            { id: 28850, name: "Rhea" },
            { id: 28844, name: "Nomad" },
            { id: 28846, name: "Anshar" },
            { id: 28848, name: "Ark" },
        ]
    },
    
    // Ships - Capital Ships
    capitals: {
        name: "Capital Ships",
        icon: "fa-rocket",
        items: [
            // Dreadnoughts
            { id: 19720, name: "Revelation" },
            { id: 19722, name: "Naglfar" },
            { id: 19724, name: "Phoenix" },
            { id: 19726, name: "Moros" },
            // Carriers
            { id: 23757, name: "Archon" },
            { id: 23915, name: "Thanatos" },
            { id: 23911, name: "Chimera" },
            { id: 23913, name: "Nidhoggur" },
            // Force Auxiliaries
            { id: 37604, name: "Apostle" },
            { id: 37606, name: "Minokawa" },
            { id: 37605, name: "Ninazu" },
            { id: 37607, name: "Lif" },
            // Supercarriers
            { id: 22852, name: "Aeon" },
            { id: 23919, name: "Nyx" },
            { id: 23917, name: "Wyvern" },
            { id: 23917, name: "Hel" },
            // Titans
            { id: 671, name: "Erebus" },
            { id: 3764, name: "Avatar" },
            { id: 11567, name: "Ragnarok" },
            { id: 20183, name: "Leviathan" },
        ]
    },
    
    // Modules - Turrets & Launchers
    turrets: {
        name: "Turrets & Launchers",
        icon: "fa-crosshairs",
        items: [
            // Projectile Turrets
            { id: 292, name: "125mm Gatling AutoCannon I" },
            { id: 293, name: "150mm Light AutoCannon I" },
            { id: 294, name: "200mm AutoCannon I" },
            { id: 295, name: "250mm Light Artillery Cannon I" },
            { id: 296, name: "280mm Howitzer Artillery I" },
            { id: 297, name: "650mm Artillery Cannon I" },
            { id: 298, name: "720mm Howitzer Artillery I" },
            { id: 299, name: "800mm Repeating Cannon I" },
            { id: 300, name: "1200mm Artillery Cannon I" },
            { id: 301, name: "1400mm Howitzer Artillery I" },
            { id: 2929, name: "125mm Gatling AutoCannon II" },
            { id: 2930, name: "150mm Light AutoCannon II" },
            { id: 2931, name: "200mm AutoCannon II" },
            { id: 2933, name: "250mm Light Artillery Cannon II" },
            { id: 2935, name: "280mm Howitzer Artillery II" },
            { id: 2937, name: "650mm Artillery Cannon II" },
            { id: 2939, name: "720mm Howitzer Artillery II" },
            { id: 2941, name: "800mm Repeating Cannon II" },
            { id: 2943, name: "1200mm Artillery Cannon II" },
            { id: 2945, name: "1400mm Howitzer Artillery II" },
            // Hybrid Turrets
            { id: 315, name: "Light Electron Blaster I" },
            { id: 316, name: "Light Ion Blaster I" },
            { id: 317, name: "Light Neutron Blaster I" },
            { id: 318, name: "Light Railgun I" },
            { id: 319, name: "Heavy Electron Blaster I" },
            { id: 320, name: "Heavy Ion Blaster I" },
            { id: 321, name: "Heavy Neutron Blaster I" },
            { id: 322, name: "Heavy Railgun I" },
            { id: 323, name: "Electron Blaster Cannon I" },
            { id: 324, name: "Ion Blaster Cannon I" },
            { id: 325, name: "Neutron Blaster Cannon I" },
            { id: 326, name: "425mm Railgun I" },
            { id: 327, name: "650mm Railgun I" },
            { id: 328, name: "Ion Blaster Cannon I" },
            { id: 329, name: "Neutron Blaster Cannon I" },
            { id: 330, name: "425mm Railgun I" },
            { id: 331, name: "75mm Gatling Rail I" },
            { id: 332, name: "Dual 150mm Railgun I" },
            { id: 333, name: "Heavy Neutron Blaster I" },
            { id: 334, name: "425mm Railgun I" },
            // Laser Turrets
            { id: 302, name: "Dual Light Beam Laser I" },
            { id: 303, name: "Dual Light Pulse Laser I" },
            { id: 304, name: "Medium Beam Laser I" },
            { id: 305, name: "Medium Pulse Laser I" },
            { id: 306, name: "Dual Heavy Beam Laser I" },
            { id: 307, name: "Dual Heavy Pulse Laser I" },
            { id: 308, name: "Mega Beam Laser I" },
            { id: 309, name: "Mega Pulse Laser I" },
            { id: 310, name: "Tachyon Beam Laser I" },
            { id: 311, name: "Tachyon Pulse Laser I" },
            // Missile Launchers
            { id: 1849, name: "Rocket Launcher I" },
            { id: 1850, name: "Light Missile Launcher I" },
            { id: 1851, name: "Heavy Missile Launcher I" },
            { id: 1852, name: "Torpedo Launcher I" },
            { id: 1853, name: "Siege Missile Launcher I" },
            { id: 2420, name: "Rapid Light Missile Launcher I" },
            { id: 2569, name: "Cruise Missile Launcher I" },
            { id: 2571, name: "Heavy Assault Missile Launcher I" },
            { id: 3244, name: "Rocket Launcher II" },
            { id: 3246, name: "Light Missile Launcher II" },
            { id: 3248, name: "Heavy Missile Launcher II" },
            { id: 3250, name: "Torpedo Launcher II" },
            { id: 3252, name: "Siege Missile Launcher II" },
            { id: 25718, name: "Rapid Heavy Missile Launcher I" },
            { id: 28544, name: "Rapid Heavy Missile Launcher II" },
        ]
    },
    
    // Modules - Shield
    shield_modules: {
        name: "Shield Modules",
        icon: "fa-shield-alt",
        items: [
            // Shield Extenders
            { id: 377, name: "Small Shield Extender I" },
            { id: 378, name: "Medium Shield Extender I" },
            { id: 379, name: "Large Shield Extender I" },
            { id: 380, name: "Micro Shield Extender I" },
            { id: 381, name: "Small Shield Extender II" },
            { id: 382, name: "Medium Shield Extender II" },
            { id: 383, name: "Large Shield Extender II" },
            { id: 384, name: "Micro Shield Extender II" },
            // Shield Hardeners
            { id: 384, name: "EM Shield Hardener I" },
            { id: 385, name: "Explosive Shield Hardener I" },
            { id: 386, name: "Kinetic Shield Hardener I" },
            { id: 387, name: "Thermal Shield Hardener I" },
            { id: 388, name: "Adaptive Invulnerability Field I" },
            { id: 389, name: "Shield Boost Amplifier I" },
            { id: 2281, name: "EM Shield Hardener II" },
            { id: 2282, name: "Explosive Shield Hardener II" },
            { id: 2283, name: "Kinetic Shield Hardener II" },
            { id: 2284, name: "Thermal Shield Hardener II" },
            { id: 2285, name: "Adaptive Invulnerability Field II" },
            { id: 2290, name: "Shield Boost Amplifier II" },
            // Shield Boosters
            { id: 361, name: "Small Shield Booster I" },
            { id: 362, name: "Medium Shield Booster I" },
            { id: 363, name: "Large Shield Booster I" },
            { id: 364, name: "X-Large Shield Booster I" },
            { id: 4027, name: "Micro Shield Booster I" },
            { id: 2183, name: "Small Shield Booster II" },
            { id: 2185, name: "Medium Shield Booster II" },
            { id: 2187, name: "Large Shield Booster II" },
            { id: 2189, name: "X-Large Shield Booster II" },
            { id: 2191, name: "Micro Shield Booster II" },
            // Other Shield
            { id: 190, name: "Shield Recharger I" },
            { id: 191, name: "Shield Power Relay I" },
            { id: 192, name: "Shield Flux Coil I" },
            { id: 393, name: "Shield Recharger II" },
            { id: 394, name: "Shield Power Relay II" },
            { id: 395, name: "Shield Flux Coil II" },
        ]
    },
    
    // Modules - Armor
    armor_modules: {
        name: "Armor Modules",
        icon: "fa-shield-alt",
        items: [
            // Armor Repairers
            { id: 338, name: "Small Armor Repairer I" },
            { id: 339, name: "Medium Armor Repairer I" },
            { id: 340, name: "Large Armor Repairer I" },
            { id: 341, name: "Small Armor Repairer II" },
            { id: 342, name: "Medium Armor Repairer II" },
            { id: 343, name: "Large Armor Repairer II" },
            // Armor Plates
            { id: 323, name: "200mm Rolled Tungsten Compact Plates" },
            { id: 324, name: "400mm Rolled Tungsten Compact Plates" },
            { id: 326, name: "800mm Rolled Tungsten Compact Plates" },
            { id: 327, name: "1600mm Rolled Tungsten Compact Plates" },
            { id: 11279, name: "200mm Crystalline Carbonide Restrained Plates" },
            { id: 11281, name: "400mm Crystalline Carbonide Restrained Plates" },
            { id: 11283, name: "800mm Crystalline Carbonide Restrained Plates" },
            { id: 11285, name: "1600mm Crystalline Carbonide Restrained Plates" },
            // Armor Hardeners
            { id: 354, name: "EM Armor Hardener I" },
            { id: 355, name: "Explosive Armor Hardener I" },
            { id: 356, name: "Kinetic Armor Hardener I" },
            { id: 357, name: "Thermal Armor Hardener I" },
            { id: 9832, name: "Adaptive Nano Plating I" },
            { id: 9836, name: "EM Armor Hardener II" },
            { id: 9838, name: "Explosive Armor Hardener II" },
            { id: 9840, name: "Kinetic Armor Hardener II" },
            { id: 9842, name: "Thermal Armor Hardener II" },
            { id: 9834, name: "Adaptive Nano Plating II" },
            // Damage Control
            { id: 2048, name: "Damage Control I" },
            { id: 2049, name: "Damage Control II" },
        ]
    },
    
    // Ammunition
    ammunition: {
        name: "Ammunition & Charges",
        icon: "fa-bullseye",
        items: [
            // Projectile Ammo
            { id: 182, name: "Carbonized Lead S" },
            { id: 183, name: "Nuclear S" },
            { id: 184, name: "Proton S" },
            { id: 185, name: "Depleted Uranium S" },
            { id: 186, name: "Titanium Sabot S" },
            { id: 187, name: "Fusion S" },
            { id: 188, name: "Phased Plasma S" },
            { id: 189, name: "EMP S" },
            { id: 190, name: "Carbonized Lead M" },
            { id: 191, name: "Nuclear M" },
            { id: 192, name: "Proton M" },
            { id: 193, name: "Depleted Uranium M" },
            { id: 194, name: "Titanium Sabot M" },
            { id: 195, name: "Fusion M" },
            { id: 196, name: "Phased Plasma M" },
            { id: 197, name: "EMP M" },
            { id: 198, name: "Carbonized Lead L" },
            { id: 199, name: "Nuclear L" },
            { id: 200, name: "Proton L" },
            { id: 201, name: "Depleted Uranium L" },
            { id: 202, name: "Titanium Sabot L" },
            { id: 203, name: "Fusion L" },
            { id: 204, name: "Phased Plasma L" },
            { id: 205, name: "EMP L" },
            { id: 206, name: "Carbonized Lead XL" },
            { id: 207, name: "Nuclear XL" },
            { id: 208, name: "Proton XL" },
            { id: 209, name: "Depleted Uranium XL" },
            { id: 210, name: "Titanium Sabot XL" },
            { id: 211, name: "Fusion XL" },
            { id: 212, name: "Phased Plasma XL" },
            { id: 213, name: "EMP XL" },
            // Hybrid Charges
            { id: 215, name: "Antimatter Charge S" },
            { id: 216, name: "Iridium Charge S" },
            { id: 217, name: "Iron Charge S" },
            { id: 218, name: "Lead Charge S" },
            { id: 219, name: "Plutonium Charge S" },
            { id: 220, name: "Thorium Charge S" },
            { id: 221, name: "Tungsten Charge S" },
            { id: 222, name: "Uranium Charge S" },
            { id: 223, name: "Antimatter Charge M" },
            { id: 224, name: "Iridium Charge M" },
            { id: 225, name: "Iron Charge M" },
            { id: 226, name: "Lead Charge M" },
            { id: 227, name: "Plutonium Charge M" },
            { id: 228, name: "Thorium Charge M" },
            { id: 229, name: "Tungsten Charge M" },
            { id: 230, name: "Uranium Charge M" },
            { id: 231, name: "Antimatter Charge L" },
            { id: 232, name: "Iridium Charge L" },
            { id: 233, name: "Iron Charge L" },
            { id: 234, name: "Lead Charge L" },
            { id: 235, name: "Plutonium Charge L" },
            { id: 236, name: "Thorium Charge L" },
            { id: 237, name: "Tungsten Charge L" },
            { id: 238, name: "Uranium Charge L" },
            // Crystals
            { id: 255, name: "Multifrequency S" },
            { id: 256, name: "Radio S" },
            { id: 257, name: "Microwave S" },
            { id: 258, name: "Infrared S" },
            { id: 259, name: "Standard S" },
            { id: 260, name: "Ultraviolet S" },
            { id: 261, name: "Xray S" },
            { id: 262, name: "Gamma S" },
            { id: 263, name: "Multifrequency M" },
            { id: 264, name: "Radio M" },
            { id: 265, name: "Microwave M" },
            { id: 266, name: "Infrared M" },
            { id: 267, name: "Standard M" },
            { id: 268, name: "Ultraviolet M" },
            { id: 269, name: "Xray M" },
            { id: 270, name: "Gamma M" },
            { id: 271, name: "Multifrequency L" },
            { id: 272, name: "Radio L" },
            { id: 273, name: "Microwave L" },
            { id: 274, name: "Infrared L" },
            { id: 275, name: "Standard L" },
            { id: 276, name: "Ultraviolet L" },
            { id: 277, name: "Xray L" },
            { id: 278, name: "Gamma L" },
            // Missiles
            { id: 245, name: "Inferno Rocket" },
            { id: 246, name: "Nova Rocket" },
            { id: 247, name: "Scourge Rocket" },
            { id: 248, name: "Mjolnir Rocket" },
            { id: 249, name: "Inferno Light Missile" },
            { id: 250, name: "Nova Light Missile" },
            { id: 251, name: "Scourge Light Missile" },
            { id: 252, name: "Mjolnir Light Missile" },
            { id: 253, name: "Inferno Heavy Missile" },
            { id: 254, name: "Nova Heavy Missile" },
            { id: 255, name: "Scourge Heavy Missile" },
            { id: 256, name: "Mjolnir Heavy Missile" },
            { id: 257, name: "Inferno Torpedo" },
            { id: 258, name: "Nova Torpedo" },
            { id: 259, name: "Scourge Torpedo" },
            { id: 260, name: "Mjolnir Torpedo" },
            { id: 261, name: "Inferno Cruise Missile" },
            { id: 262, name: "Nova Cruise Missile" },
            { id: 263, name: "Scourge Cruise Missile" },
            { id: 264, name: "Mjolnir Cruise Missile" },
            { id: 265, name: "Inferno XL Torpedo" },
            { id: 266, name: "Nova XL Torpedo" },
            { id: 267, name: "Scourge XL Torpedo" },
            { id: 268, name: "Mjolnir XL Torpedo" },
            // Cap Booster Charges
            { id: 1123, name: "Cap Booster 25" },
            { id: 1124, name: "Cap Booster 50" },
            { id: 1125, name: "Cap Booster 75" },
            { id: 1126, name: "Cap Booster 100" },
            { id: 1127, name: "Cap Booster 150" },
            { id: 1128, name: "Cap Booster 200" },
            { id: 1129, name: "Cap Booster 400" },
            { id: 1130, name: "Cap Booster 800" },
            { id: 1131, name: "Cap Booster 3200" },
            { id: 1132, name: "Cap Booster 6400" },
            { id: 28668, name: "Nanite Repair Paste" },
        ]
    },
    
    // Trade Goods
    trade_goods: {
        name: "Trade Goods",
        icon: "fa-coins",
        items: [
            // PLEX and Services
            { id: 44992, name: "30 Day Pilot's License Extension (PLEX)" },
            { id: 48568, name: "Daily Alpha Injector" },
            { id: 40520, name: "Large Skill Injector" },
            { id: 40519, name: "Small Skill Injector" },
            { id: 30375, name: "Skill Extractor" },
            { id: 34134, name: "Multiple Pilot Training Certificate" },
            // Filaments
            { id: 54959, name: "Noise-25 'Filament'" },
            { id: 54961, name: "Noise-5 'Filament'" },
            { id: 54963, name: "Signal-25 'Filament'" },
            { id: 54965, name: "Signal-5 'Filament'" },
            { id: 55994, name: "Firestorm Filament" },
            { id: 56002, name: "Firestorm III Filament" },
            { id: 56005, name: "Firestorm V Filament" },
            { id: 55995, name: "Exotic Filament" },
            { id: 56003, name: "Exotic III Filament" },
            { id: 56006, name: "Exotic V Filament" },
            { id: 55996, name: "Gamma Filament" },
            { id: 56004, name: "Gamma III Filament" },
            { id: 56007, name: "Gamma V Filament" },
            { id: 55997, name: "Electrical Filament" },
            { id: 56000, name: "Electrical III Filament" },
            { id: 56008, name: "Electrical V Filament" },
            { id: 55998, name: "Dark Filament" },
            { id: 56001, name: "Dark III Filament" },
            { id: 56009, name: "Dark V Filament" },
            // Triglavian stuff
            { id: 48184, name: "Triglavian Survey Database" },
            { id: 48185, name: "Triglavian Data" },
        ]
    },
    
    // Drones
    drones: {
        name: "Drones",
        icon: "fa-fighter-jet",
        items: [
            // Light Drones
            { id: 2464, name: "Acolyte I" },
            { id: 2466, name: "Hobgoblin I" },
            { id: 2468, name: "Hornet I" },
            { id: 2470, name: "Warrior I" },
            { id: 2472, name: "Praetor I" },
            { id: 2474, name: "Infiltrator I" },
            { id: 2476, name: "Valkyrie I" },
            { id: 2478, name: "Vespa I" },
            { id: 2480, name: "Hammerhead I" },
            { id: 2482, name: "Berserker I" },
            { id: 2484, name: "Wasp I" },
            { id: 2486, name: "Ogre I" },
            { id: 2488, name: "Bouncer I" },
            { id: 2490, name: "Garde I" },
            { id: 2492, name: "Curator I" },
            { id: 2494, name: "Warden I" },
            // T2 Light
            { id: 2205, name: "Acolyte II" },
            { id: 2207, name: "Hobgoblin II" },
            { id: 2209, name: "Hornet II" },
            { id: 2211, name: "Warrior II" },
            // T2 Medium
            { id: 2303, name: "Praetor II" },
            { id: 2305, name: "Infiltrator II" },
            { id: 2307, name: "Valkyrie II" },
            { id: 2309, name: "Vespa II" },
            { id: 2311, name: "Hammerhead II" },
            // T2 Heavy
            { id: 2313, name: "Berserker II" },
            { id: 2315, name: "Wasp II" },
            { id: 2317, name: "Ogre II" },
            // Sentry
            { id: 2319, name: "Bouncer II" },
            { id: 2321, name: "Garde II" },
            { id: 2323, name: "Curator II" },
            { id: 2325, name: "Warden II" },
            // EWAR Drones
            { id: 23771, name: "Acolyte EV-300" },
            { id: 23773, name: "Infiltrator EV-300" },
            { id: 23775, name: "Vespa EC-300" },
            { id: 23777, name: "Hornet EC-300" },
            { id: 23779, name: "Hammerhead EC-300" },
            { id: 23781, name: "Ogre EC-300" },
            // Utility Drones
            { id: 23783, name: "Acolyte TD-300" },
            { id: 23785, name: "Infiltrator TD-300" },
            { id: 23787, name: "Vespa TD-300" },
            { id: 23789, name: "Hornet TD-300" },
            { id: 23791, name: "Hammerhead TD-300" },
            { id: 23793, name: "Ogre TD-300" },
        ]
    },
    
    // Implants
    implants: {
        name: "Implants & Boosters",
        icon: "fa-brain",
        items: [
            // Attribute Enhancers - Limited
            { id: 10223, name: "Limited Ocular Filter" },
            { id: 10224, name: "Limited Memory Augmentation" },
            { id: 10225, name: "Limited Neural Boost" },
            { id: 10226, name: "Limited Cybernetic Subprocessor" },
            { id: 10227, name: "Limited Magnetic Field Stabilizer" },
            { id: 10228, name: "Limited Social Adaptation Chip" },
            { id: 10229, name: "Limited Eidetic Memory Interface" },
            // Attribute Enhancers - Basic
            { id: 10216, name: "Ocular Filter - Basic" },
            { id: 10217, name: "Memory Augmentation - Basic" },
            { id: 10218, name: "Neural Boost - Basic" },
            { id: 10219, name: "Cybernetic Subprocessor - Basic" },
            { id: 10220, name: "Magnetic Field Stabilizer - Basic" },
            { id: 10221, name: "Social Adaptation Chip - Basic" },
            { id: 10222, name: "Eidetic Memory Interface - Basic" },
            // Attribute Enhancers - Standard
            { id: 10208, name: "Ocular Filter - Standard" },
            { id: 10209, name: "Memory Augmentation - Standard" },
            { id: 10210, name: "Neural Boost - Standard" },
            { id: 10211, name: "Cybernetic Subprocessor - Standard" },
            { id: 10212, name: "Magnetic Field Stabilizer - Standard" },
            { id: 10213, name: "Social Adaptation Chip - Standard" },
            { id: 10214, name: "Eidetic Memory Interface - Standard" },
            // Attribute Enhancers - Advanced
            { id: 10200, name: "Ocular Filter - Advanced" },
            { id: 10201, name: "Memory Augmentation - Advanced" },
            { id: 10202, name: "Neural Boost - Advanced" },
            { id: 10203, name: "Cybernetic Subprocessor - Advanced" },
            { id: 10204, name: "Magnetic Field Stabilizer - Advanced" },
            { id: 10205, name: "Social Adaptation Chip - Advanced" },
            { id: 10206, name: "Eidetic Memory Interface - Advanced" },
            // Attribute Enhancers - Elite
            { id: 339, name: "High-grade Ascendancy Alpha" },
            { id: 340, name: "High-grade Ascendancy Beta" },
            { id: 341, name: "High-grade Ascendancy Gamma" },
            { id: 342, name: "High-grade Ascendancy Delta" },
            { id: 343, name: "High-grade Ascendancy Epsilon" },
            { id: 344, name: "High-grade Ascendancy Omega" },
            // Skill Hardwirings - Common
            { id: 20494, name: "Inherent Implants 'Noble' Repair Systems RS-601" },
            { id: 20495, name: "Inherent Implants 'Noble' Repair Systems RS-602" },
            { id: 20496, name: "Inherent Implants 'Noble' Repair Systems RS-603" },
            { id: 20497, name: "Inherent Implants 'Noble' Repair Systems RS-604" },
            { id: 20498, name: "Inherent Implants 'Noble' Repair Systems RS-605" },
            { id: 20499, name: "Inherent Implants 'Noble' Repair Systems RS-606" },
            // Combat Boosters
            { id: 28665, name: "Standard Blue Pill Booster" },
            { id: 28666, name: "Standard Crash Booster" },
            { id: 28667, name: "Standard Drop Booster" },
            { id: 28669, name: "Standard Exile Booster" },
            { id: 28670, name: "Standard Frentix Booster" },
            { id: 28671, name: "Standard Mindflood Booster" },
            { id: 28672, name: "Standard X-Instinct Booster" },
            { id: 28673, name: "Strong Blue Pill Booster" },
            { id: 28674, name: "Strong Crash Booster" },
            { id: 28675, name: "Strong Drop Booster" },
            { id: 28676, name: "Strong Exile Booster" },
            { id: 28677, name: "Strong Frentix Booster" },
            { id: 28678, name: "Strong Mindflood Booster" },
            { id: 28679, name: "Strong X-Instinct Booster" },
        ]
    },
    
    // Blueprints
    blueprints: {
        name: "Blueprints",
        icon: "fa-scroll",
        items: [
            // Ship BPOs - Frigates
            { id: 683, name: "Rifter Blueprint" },
            { id: 684, name: "Condor Blueprint" },
            { id: 685, name: "Executioner Blueprint" },
            { id: 686, name: "Atron Blueprint" },
            { id: 687, name: "Stabber Blueprint" },
            { id: 688, name: "Moa Blueprint" },
            { id: 689, name: "Maller Blueprint" },
            { id: 690, name: "Vexor Blueprint" },
            { id: 691, name: "Thorax Blueprint" },
            { id: 692, name: "Rupture Blueprint" },
            { id: 693, name: "Caracal Blueprint" },
            { id: 694, name: "Omen Blueprint" },
            { id: 695, name: "Raven Blueprint" },
            { id: 696, name: "Apocalypse Blueprint" },
            { id: 697, name: "Megathron Blueprint" },
            { id: 698, name: "Dominix Blueprint" },
            // Module BPOs
            { id: 699, name: "Small Armor Repairer I Blueprint" },
            { id: 700, name: "Medium Armor Repairer I Blueprint" },
            { id: 701, name: "Large Armor Repairer I Blueprint" },
            { id: 702, name: "Small Shield Booster I Blueprint" },
            { id: 703, name: "Medium Shield Booster I Blueprint" },
            { id: 704, name: "Large Shield Booster I Blueprint" },
            { id: 705, name: "Antimatter Charge S Blueprint" },
            { id: 706, name: "Iridium Charge S Blueprint" },
            { id: 707, name: "Iron Charge S Blueprint" },
            { id: 708, name: "Lead Charge S Blueprint" },
            { id: 709, name: "Plutonium Charge S Blueprint" },
            { id: 710, name: "Thorium Charge S Blueprint" },
            { id: 711, name: "Tungsten Charge S Blueprint" },
            { id: 712, name: "Uranium Charge S Blueprint" },
        ]
    },
    
    // Skillbooks
    skills: {
        name: "Skillbooks",
        icon: "fa-graduation-cap",
        items: [
            { id: 2403, name: "Advanced Planetology" },
            { id: 2406, name: "Planetology" },
            { id: 2495, name: "Interplanetary Consolidation" },
            { id: 2505, name: "Command Center Upgrades" },
            { id: 3184, name: "ORE Hauler" },
            { id: 3300, name: "Gunnery" },
            { id: 3301, name: "Small Hybrid Turret" },
            { id: 3302, name: "Small Projectile Turret" },
            { id: 3303, name: "Small Energy Turret" },
            { id: 3304, name: "Medium Hybrid Turret" },
            { id: 3305, name: "Medium Projectile Turret" },
            { id: 3306, name: "Medium Energy Turret" },
            { id: 3307, name: "Large Hybrid Turret" },
            { id: 3308, name: "Large Projectile Turret" },
            { id: 3309, name: "Large Energy Turret" },
            { id: 3310, name: "Rapid Firing" },
            { id: 3311, name: "Sharpshooter" },
            { id: 3312, name: "Motion Prediction" },
            { id: 3315, name: "Surgical Strike" },
            { id: 3316, name: "Controlled Bursts" },
            { id: 3317, name: "Trajectory Analysis" },
            { id: 3318, name: "Weapon Upgrades" },
            { id: 3319, name: "Missile Launcher Operation" },
            { id: 3320, name: "Rockets" },
            { id: 3321, name: "Light Missiles" },
            { id: 3322, name: "Auto-Targeting Missiles" },
            { id: 3323, name: "Defender Missiles" },
            { id: 3324, name: "Heavy Missiles" },
            { id: 3325, name: "Torpedoes" },
            { id: 3326, name: "Cruise Missiles" },
            { id: 3327, name: "Spaceship Command" },
            { id: 3328, name: "Gallente Frigate" },
            { id: 3329, name: "Minmatar Frigate" },
            { id: 3330, name: "Caldari Frigate" },
            { id: 3331, name: "Amarr Frigate" },
            { id: 3332, name: "Gallente Cruiser" },
            { id: 3333, name: "Minmatar Cruiser" },
            { id: 3334, name: "Caldari Cruiser" },
            { id: 3335, name: "Amarr Cruiser" },
            { id: 3336, name: "Gallente Battleship" },
            { id: 3337, name: "Minmatar Battleship" },
            { id: 3338, name: "Caldari Battleship" },
            { id: 3339, name: "Amarr Battleship" },
            { id: 3340, name: "Gallente Hauler" },
            { id: 3341, name: "Minmatar Hauler" },
            { id: 3342, name: "Caldari Hauler" },
            { id: 3343, name: "Amarr Hauler" },
            { id: 3344, name: "Gallente Titan" },
            { id: 3345, name: "Minmatar Titan" },
            { id: 3346, name: "Caldari Titan" },
            { id: 3347, name: "Amarr Titan" },
            { id: 3348, name: "Leadership" },
            { id: 3349, name: "Skirmish Command" },
            { id: 3350, name: "Shield Command" },
            { id: 3351, name: "Shield Command Specialist" },
            { id: 3352, name: "Information Command Specialist" },
            { id: 3354, name: "Command Burst Specialist" },
            { id: 3355, name: "Social" },
            { id: 3356, name: "Negotiation" },
            { id: 3357, name: "Diplomacy" },
            { id: 3358, name: "Fast Talk" },
            { id: 3359, name: "Connections" },
            { id: 3361, name: "Criminal Connections" },
            { id: 3363, name: "Corporation Management" },
            { id: 3368, name: "Diplomatic Relations" },
            { id: 3373, name: "Starbase Defense Management" },
            { id: 3380, name: "Industry" },
            { id: 3385, name: "Reprocessing" },
            { id: 3386, name: "Mining" },
            { id: 3387, name: "Mass Production" },
            { id: 3388, name: "Advanced Industry" },
            { id: 3389, name: "Reprocessing Efficiency" },
            { id: 3392, name: "Mechanics" },
            { id: 3393, name: "Repair Systems" },
            { id: 3394, name: "Hull Upgrades" },
            { id: 3395, name: "Advanced Small Ship Construction" },
            { id: 3396, name: "Advanced Industrial Ship Construction" },
            { id: 3397, name: "Advanced Medium Ship Construction" },
            { id: 3398, name: "Advanced Large Ship Construction" },
            { id: 3400, name: "Outpost Construction" },
            { id: 3402, name: "Science" },
            { id: 3403, name: "Research" },
            { id: 3405, name: "Biology" },
            { id: 3406, name: "Laboratory Operation" },
            { id: 3408, name: "Sleeper Encryption Methods" },
            { id: 3409, name: "Metallurgy" },
            { id: 3410, name: "Astrogeology" },
            { id: 3411, name: "Cybernetics" },
            { id: 3412, name: "Astrometrics" },
            { id: 3413, name: "Power Grid Management" },
            { id: 3416, name: "Shield Operation" },
            { id: 3417, name: "Capacitor Systems Operation" },
            { id: 3418, name: "Capacitor Management" },
            { id: 3419, name: "Shield Management" },
            { id: 3420, name: "Tactical Shield Manipulation" },
            { id: 3421, name: "Energy Pulse Weapons" },
            { id: 3422, name: "Shield Emission Systems" },
            { id: 3423, name: "Capacitor Emission Systems" },
            { id: 3424, name: "Energy Grid Upgrades" },
            { id: 3425, name: "Shield Upgrades" },
            { id: 3426, name: "CPU Management" },
            { id: 3427, name: "Electronic Warfare" },
            { id: 3428, name: "Long Range Targeting" },
            { id: 3429, name: "Target Management" },
            { id: 3430, name: "Advanced Target Management" },
            { id: 3431, name: "Signature Analysis" },
            { id: 3432, name: "Electronics Upgrades" },
            { id: 3433, name: "Sensor Linking" },
            { id: 3434, name: "Weapon Disruption" },
            { id: 3435, name: "Propulsion Jamming" },
            { id: 3436, name: "Drones" },
            { id: 3437, name: "Drone Avionics" },
            { id: 3438, name: "Mining Drone Operation" },
            { id: 3439, name: "Repair Drone Operation" },
            { id: 3440, name: "Salvage Drone Operation" },
            { id: 3441, name: "Heavy Drone Operation" },
            { id: 3442, name: "Drone Interfacing" },
            { id: 3443, name: "Trade" },
            { id: 3444, name: "Retail" },
            { id: 3446, name: "Broker Relations" },
            { id: 3447, name: "Visibility" },
            { id: 3449, name: "Navigation" },
            { id: 3450, name: "Afterburner" },
            { id: 3451, name: "Fuel Conservation" },
            { id: 3452, name: "Acceleration Control" },
            { id: 3453, name: "Evasive Maneuvering" },
            { id: 3454, name: "High Speed Maneuvering" },
            { id: 3455, name: "Warp Drive Operation" },
            { id: 3456, name: "Jump Drive Operation" },
            { id: 3551, name: "Survey" },
            { id: 3731, name: "Megacorp Management" },
            { id: 3732, name: "Empire Control" },
            { id: 3893, name: "Mining Connections" },
            { id: 3894, name: "Distribution Connections" },
            { id: 3895, name: "Security Connections" },
            { id: 4385, name: "Micro Jump Drive Operation" },
            { id: 4411, name: "Signature Masking" },
            { id: 11082, name: "Small Railgun Specialization" },
            { id: 11083, name: "Small Beam Laser Specialization" },
            { id: 11084, name: "Small Autocannon Specialization" },
            { id: 11207, name: "Advanced Weapon Upgrades" },
            { id: 11395, name: "Deep Core Mining" },
            { id: 11433, name: "High Energy Physics" },
            { id: 11441, name: "Plasma Physics" },
            { id: 11442, name: "Nanite Engineering" },
            { id: 11443, name: "Hydromagnetic Physics" },
            { id: 11444, name: "Amarr Starship Engineering" },
            { id: 11445, name: "Minmatar Starship Engineering" },
            { id: 11446, name: "Graviton Physics" },
            { id: 11447, name: "Laser Physics" },
            { id: 11448, name: "Electromagnetic Physics" },
            { id: 11449, name: "Rocket Science" },
            { id: 11450, name: "Gallente Starship Engineering" },
            { id: 11451, name: "Nuclear Physics" },
            { id: 11452, name: "Mechanical Engineering" },
            { id: 11453, name: "Electronic Engineering" },
            { id: 11454, name: "Caldari Starship Engineering" },
            { id: 11455, name: "Quantum Physics" },
            { id: 11487, name: "Astronautic Engineering" },
            { id: 11529, name: "Molecular Engineering" },
            { id: 11566, name: "Thermal Shield Compensation" },
            { id: 11569, name: "Armored Command Specialist" },
            { id: 11572, name: "Skirmish Command Specialist" },
            { id: 11574, name: "Wing Command" },
            { id: 11579, name: "Cloaking" },
            { id: 11584, name: "Anchoring" },
            { id: 12092, name: "Interceptors" },
            { id: 12093, name: "Covert Ops" },
            { id: 12095, name: "Assault Frigates" },
            { id: 12096, name: "Logistics Cruisers" },
            { id: 12098, name: "Interdictors" },
            { id: 12179, name: "Research Project Management" },
            { id: 12189, name: "Mercoxit Ore Processing" },
            { id: 12196, name: "Scrapmetal Processing" },
            { id: 12201, name: "Small Artillery Specialization" },
            { id: 12202, name: "Medium Artillery Specialization" },
            { id: 12203, name: "Large Artillery Specialization" },
            { id: 12204, name: "Medium Beam Laser Specialization" },
            { id: 12205, name: "Large Beam Laser Specialization" },
            { id: 12206, name: "Medium Railgun Specialization" },
            { id: 12207, name: "Large Railgun Specialization" },
            { id: 12208, name: "Medium Autocannon Specialization" },
            { id: 12209, name: "Large Autocannon Specialization" },
            { id: 12210, name: "Small Blaster Specialization" },
            { id: 12211, name: "Medium Blaster Specialization" },
            { id: 12212, name: "Large Blaster Specialization" },
            { id: 12213, name: "Small Pulse Laser Specialization" },
            { id: 12214, name: "Medium Pulse Laser Specialization" },
            { id: 12215, name: "Large Pulse Laser Specialization" },
            { id: 12241, name: "Sovereignty" },
            { id: 12305, name: "Drone Navigation" },
            { id: 12365, name: "EM Shield Compensation" },
            { id: 12366, name: "Kinetic Shield Compensation" },
            { id: 12367, name: "Explosive Shield Compensation" },
            { id: 12441, name: "Missile Bombardment" },
            { id: 12442, name: "Missile Projection" },
            { id: 12484, name: "Amarr Drone Specialization" },
            { id: 12485, name: "Minmatar Drone Specialization" },
            { id: 12486, name: "Gallente Drone Specialization" },
            { id: 12487, name: "Caldari Drone Specialization" },
            { id: 13278, name: "Archaeology" },
            { id: 13279, name: "Remote Sensing" },
            { id: 16069, name: "Remote Armor Repair Systems" },
            { id: 16281, name: "Ice Harvesting" },
            { id: 16591, name: "Heavy Assault Cruisers" },
            { id: 16594, name: "Procurement" },
            { id: 16595, name: "Daytrading" },
            { id: 16596, name: "Wholesale" },
            { id: 16597, name: "Advanced Broker Relations" },
            { id: 16598, name: "Marketing" },
            { id: 16622, name: "Accounting" },
            { id: 17940, name: "Mining Barge" },
            { id: 18025, name: "Ice Processing" },
            { id: 18580, name: "Tycoon" },
            { id: 19719, name: "Transport Ships" },
            { id: 19759, name: "Long Distance Jamming" },
            { id: 19760, name: "Frequency Modulation" },
            { id: 19761, name: "Signal Dispersion" },
            { id: 19766, name: "Signal Suppression" },
            { id: 19767, name: "Weapon Destabilization" },
            { id: 19921, name: "Target Painting" },
            { id: 19922, name: "Signature Focusing" },
            { id: 20209, name: "Rocket Specialization" },
            { id: 20210, name: "Light Missile Specialization" },
            { id: 20211, name: "Heavy Missile Specialization" },
            { id: 20212, name: "Cruise Missile Specialization" },
            { id: 20213, name: "Torpedo Specialization" },
            { id: 20312, name: "Guided Missile Precision" },
            { id: 20314, name: "Target Navigation Prediction" },
            { id: 20315, name: "Warhead Upgrades" },
            { id: 20327, name: "Capital Energy Turret" },
            { id: 20342, name: "Advanced Spaceship Command" },
            { id: 20433, name: "Talocan Technology" },
            { id: 20494, name: "Armored Command" },
            { id: 20495, name: "Information Command" },
            { id: 20524, name: "Amarr Freighter" },
            { id: 20525, name: "Amarr Dreadnought" },
            { id: 20526, name: "Caldari Freighter" },
            { id: 20527, name: "Gallente Freighter" },
            { id: 20528, name: "Minmatar Freighter" },
            { id: 20530, name: "Caldari Dreadnought" },
            { id: 20531, name: "Gallente Dreadnought" },
            { id: 20532, name: "Minmatar Dreadnought" },
            { id: 20533, name: "Capital Ships" },
            { id: 21059, name: "Shield Compensation" },
            { id: 21071, name: "Rapid Launch" },
            { id: 21603, name: "Cynosural Field Theory" },
            { id: 21610, name: "Jump Fuel Conservation" },
            { id: 21611, name: "Jump Drive Calibration" },
            { id: 21666, name: "Capital Hybrid Turret" },
            { id: 21667, name: "Capital Projectile Turret" },
            { id: 21668, name: "XL Torpedoes" },
            { id: 21718, name: "Hacking" },
            { id: 21789, name: "Sleeper Technology" },
            { id: 21790, name: "Caldari Encryption Methods" },
            { id: 21791, name: "Minmatar Encryption Methods" },
            { id: 21802, name: "Capital Shield Operation" },
            { id: 21803, name: "Capital Repair Systems" },
            { id: 22043, name: "Tactical Weapon Reconfiguration" },
            { id: 22242, name: "Capital Ship Construction" },
            { id: 22536, name: "Mining Foreman" },
            { id: 22541, name: "Mining Drone Specialization" },
            { id: 22551, name: "Exhumers" },
            { id: 22552, name: "Mining Director" },
            { id: 22578, name: "Mining Upgrades" },
            { id: 22761, name: "Recon Ships" },
            { id: 22806, name: "EM Armor Compensation" },
            { id: 22807, name: "Explosive Armor Compensation" },
            { id: 22808, name: "Kinetic Armor Compensation" },
            { id: 22809, name: "Thermal Armor Compensation" },
            { id: 23069, name: "Fighters" },
            { id: 23087, name: "Amarr Encryption Methods" },
            { id: 23121, name: "Gallente Encryption Methods" },
            { id: 23123, name: "Takmahl Technology" },
            { id: 23124, name: "Yan Jung Technology" },
            { id: 23566, name: "Advanced Drone Avionics" },
            { id: 23594, name: "Sentry Drone Interfacing" },
            { id: 23606, name: "Drone Sharpshooting" },
            { id: 23618, name: "Drone Durability" },
            { id: 23950, name: "Command Ships" },
            { id: 24241, name: "Light Drone Operation" },
            { id: 24242, name: "Infomorph Psychology" },
            { id: 24268, name: "Supply Chain Management" },
            { id: 24270, name: "Scientific Networking" },
            { id: 24311, name: "Amarr Carrier" },
            { id: 24312, name: "Caldari Carrier" },
            { id: 24313, name: "Gallente Carrier" },
            { id: 24314, name: "Minmatar Carrier" },
            { id: 24562, name: "Jump Portal Generation" },
            { id: 24563, name: "Doomsday Operation" },
            { id: 24568, name: "Capital Remote Armor Repair Systems" },
            { id: 24571, name: "Capital Shield Emission Systems" },
            { id: 24572, name: "Capital Capacitor Emission Systems" },
            { id: 24606, name: "Cloning Facility Operation" },
            { id: 24613, name: "Fighter Hangar Management" },
            { id: 24624, name: "Advanced Laboratory Operation" },
            { id: 24625, name: "Advanced Mass Production" },
            { id: 24764, name: "Fleet Command" },
            { id: 25233, name: "Corporation Contracting" },
            { id: 25235, name: "Contracting" },
            { id: 25530, name: "Neurotoxin Recovery" },
            { id: 25538, name: "Neurotoxin Control" },
            { id: 25544, name: "Gas Cloud Harvesting" },
            { id: 25718, name: "Heavy Assault Missile Specialization" },
            { id: 25719, name: "Heavy Assault Missiles" },
            { id: 25739, name: "Astrometric Rangefinding" },
            { id: 25810, name: "Astrometric Pinpointing" },
            { id: 25811, name: "Astrometric Acquisition" },
            { id: 25863, name: "Salvaging" },
            { id: 26224, name: "Drug Manufacturing" },
            { id: 26252, name: "Jury Rigging" },
            { id: 26253, name: "Armor Rigging" },
            { id: 26254, name: "Astronautics Rigging" },
            { id: 26255, name: "Drones Rigging" },
            { id: 26256, name: "Electronic Superiority Rigging" },
            { id: 26257, name: "Projectile Weapon Rigging" },
            { id: 26258, name: "Energy Weapon Rigging" },
            { id: 26259, name: "Hybrid Weapon Rigging" },
            { id: 26260, name: "Launcher Rigging" },
            { id: 26261, name: "Shield Rigging" },
            { id: 27902, name: "Remote Hull Repair Systems" },
            { id: 27906, name: "Tactical Logistics Reconfiguration" },
            { id: 27911, name: "Burst Projector Operation" },
            { id: 27936, name: "Capital Remote Hull Repair Systems" },
            { id: 28073, name: "Bomb Deployment" },
            { id: 28164, name: "Thermodynamics" },
            { id: 28374, name: "Capital Industrial Ships" },
            { id: 28585, name: "Capital Industrial Reconfiguration" },
            { id: 28609, name: "Heavy Interdiction Cruisers" },
            { id: 28615, name: "Electronic Attack Ships" },
            { id: 28656, name: "Black Ops" },
            { id: 28667, name: "Marauders" },
            { id: 28879, name: "Nanite Operation" },
            { id: 28880, name: "Nanite Interfacing" },
            { id: 29029, name: "Jump Freighters" },
            { id: 29637, name: "Industrial Command Ships" },
            { id: 30324, name: "Defensive Subsystem Technology" },
            { id: 30325, name: "Core Subsystem Technology" },
            { id: 30327, name: "Offensive Subsystem Technology" },
            { id: 30532, name: "Amarr Defensive Systems" },
            { id: 30537, name: "Amarr Offensive Systems" },
            { id: 30538, name: "Amarr Propulsion Systems" },
            { id: 30539, name: "Amarr Core Systems" },
            { id: 30540, name: "Gallente Defensive Systems" },
            { id: 30544, name: "Caldari Defensive Systems" },
            { id: 30545, name: "Minmatar Defensive Systems" },
            { id: 30546, name: "Gallente Core Systems" },
            { id: 30547, name: "Minmatar Core Systems" },
            { id: 30548, name: "Caldari Core Systems" },
            { id: 30549, name: "Caldari Offensive Systems" },
            { id: 30550, name: "Gallente Offensive Systems" },
            { id: 30551, name: "Minmatar Offensive Systems" },
            { id: 30552, name: "Caldari Propulsion Systems" },
            { id: 30553, name: "Gallente Propulsion Systems" },
            { id: 30554, name: "Minmatar Propulsion Systems" },
            { id: 30650, name: "Amarr Strategic Cruiser" },
            { id: 30651, name: "Caldari Strategic Cruiser" },
            { id: 30652, name: "Gallente Strategic Cruiser" },
            { id: 30653, name: "Minmatar Strategic Cruiser" },
            { id: 30788, name: "Propulsion Subsystem Technology" },
            { id: 32339, name: "Heavy Fighters" },
            { id: 32435, name: "XL Cruise Missiles" },
            { id: 32797, name: "Resistance Phasing" },
            { id: 32918, name: "Mining Frigate" },
            { id: 32999, name: "Magnetometric Sensor Compensation" },
            { id: 33000, name: "Gravimetric Sensor Compensation" },
            { id: 33001, name: "Ladar Sensor Compensation" },
            { id: 33002, name: "Radar Sensor Compensation" },
            { id: 33078, name: "Armor Layering" },
            { id: 33091, name: "Amarr Destroyer" },
            { id: 33092, name: "Caldari Destroyer" },
            { id: 33093, name: "Gallente Destroyer" },
            { id: 33094, name: "Minmatar Destroyer" },
            { id: 33095, name: "Amarr Battlecruiser" },
            { id: 33096, name: "Caldari Battlecruiser" },
            { id: 33097, name: "Gallente Battlecruiser" },
            { id: 33098, name: "Minmatar Battlecruiser" },
            { id: 33399, name: "Infomorph Synchronizing" },
            { id: 33407, name: "Advanced Infomorph Psychology" },
            { id: 33467, name: "Customs Code Expertise" },
            { id: 33699, name: "Medium Drone Operation" },
            { id: 33856, name: "Expedition Frigates" },
            { id: 34327, name: "ORE Freighter" },
            { id: 34390, name: "Amarr Tactical Destroyer" },
            { id: 34533, name: "Minmatar Tactical Destroyer" },
            { id: 35680, name: "Caldari Tactical Destroyer" },
            { id: 35685, name: "Gallente Tactical Destroyer" },
            { id: 37615, name: "Command Destroyers" },
            { id: 37796, name: "Structure Missile Systems" },
            { id: 37797, name: "Structure Doomsday Operation" },
            { id: 37798, name: "Structure Electronic Systems" },
            { id: 37799, name: "Structure Engineering Systems" },
            { id: 40328, name: "Logistics Frigates" },
            { id: 40572, name: "Light Fighters" },
            { id: 40573, name: "Support Fighters" },
            { id: 41403, name: "Capital Autocannon Specialization" },
            { id: 41404, name: "Capital Artillery Specialization" },
            { id: 41405, name: "Capital Blaster Specialization" },
            { id: 41406, name: "Capital Railgun Specialization" },
            { id: 41407, name: "Capital Pulse Laser Specialization" },
            { id: 41408, name: "Capital Beam Laser Specialization" },
            { id: 41409, name: "XL Torpedo Specialization" },
            { id: 41410, name: "XL Cruise Missile Specialization" },
            { id: 41537, name: "Doomsday Rapid Firing" },
            { id: 43702, name: "Ice Harvesting Drone Operation" },
            { id: 43703, name: "Ice Harvesting Drone Specialization" },
            { id: 43728, name: "Spatial Phenomena Generation" },
            { id: 44067, name: "Invulnerability Core Operation" },
            { id: 45746, name: "Reactions" },
            { id: 45748, name: "Mass Reactions" },
            { id: 45749, name: "Advanced Mass Reactions" },
            { id: 45750, name: "Remote Reactions" },
            { id: 46152, name: "Ubiquitous Moon Ore Processing" },
            { id: 46153, name: "Common Moon Ore Processing" },
            { id: 46154, name: "Uncommon Moon Ore Processing" },
            { id: 46155, name: "Rare Moon Ore Processing" },
            { id: 46156, name: "Exceptional Moon Ore Processing" },
            { id: 47445, name: "Flag Cruisers" },
            { id: 47867, name: "Precursor Frigate" },
            { id: 47868, name: "Precursor Cruiser" },
            { id: 47869, name: "Precursor Battleship" },
            { id: 47870, name: "Small Precursor Weapon" },
            { id: 47871, name: "Medium Precursor Weapon" },
            { id: 47872, name: "Large Precursor Weapon" },
            { id: 47873, name: "Small Disintegrator Specialization" },
            { id: 47874, name: "Medium Disintegrator Specialization" },
            { id: 47875, name: "Large Disintegrator Specialization" },
            { id: 49742, name: "Precursor Destroyer" },
            { id: 49743, name: "Precursor Battlecruiser" },
            { id: 52307, name: "Triglavian Quantum Engineering" },
            { id: 52308, name: "Triglavian Encryption Methods" },
            { id: 52997, name: "Precursor Dreadnought" },
            { id: 52998, name: "Capital Precursor Weapon" },
            { id: 54794, name: "EDENCOM Battleship" },
            { id: 54826, name: "Large Vorton Projector" },
            { id: 54827, name: "Small Vorton Specialization" },
            { id: 54828, name: "Medium Vorton Specialization" },
            { id: 54829, name: "Large Vorton Specialization" },
            { id: 54840, name: "Vorton Power Amplification" },
            { id: 54841, name: "Vorton Arc Guidance" },
            { id: 55025, name: "Upwell Encryption Methods" },
            { id: 55031, name: "EDENCOM Frigate" },
            { id: 55032, name: "EDENCOM Cruiser" },
            { id: 55033, name: "Vorton Projector Operation" },
            { id: 55034, name: "Small Vorton Projector" },
            { id: 55035, name: "Medium Vorton Projector" },
            { id: 55511, name: "Vorton Arc Extension" },
            { id: 57164, name: "Salvage Drone Specialization" },
            { id: 57317, name: "Fleet Formations" },
            { id: 57318, name: "Fleet Coordination" },
            { id: 58956, name: "Industrial Reconfiguration" },
            { id: 60377, name: "Simple Ore Processing" },
            { id: 60378, name: "Coherent Ore Processing" },
            { id: 60379, name: "Variegated Ore Processing" },
            { id: 60380, name: "Complex Ore Processing" },
            { id: 60381, name: "Abyssal Ore Processing" },
            { id: 60515, name: "Mutated Drone Specialization" },
            { id: 62450, name: "Shipboard Compression Technology" },
            { id: 62451, name: "Capital Shipboard Compression Technology" },
            { id: 62452, name: "Gas Decompression Efficiency" },
            { id: 62453, name: "Fleet Compression Logistics" },
            { id: 73910, name: "Elite Infomorph Psychology" },
            { id: 73912, name: "Advanced Contracting" },
            { id: 77725, name: "Advanced Capital Ship Construction" },
            { id: 77738, name: "Lancer Dreadnoughts" },
            { id: 77739, name: "Disruptive Lance Operation" },
            { id: 81032, name: "Upwell Hauler" },
            { id: 81044, name: "Upwell Freighter" },
            { id: 81050, name: "Upwell Starship Engineering" },
            { id: 81364, name: "Mass Sequencing" },
            { id: 81365, name: "Industrial Sequencing" },
            { id: 81366, name: "Parallel Sequencing" },
            { id: 81367, name: "Multi-thread Sequencing" },
            { id: 81368, name: "Hub Promotion" },
            { id: 81369, name: "Hub Algorithm Optimization" },
            { id: 81370, name: "Studio Management" },
            { id: 81371, name: "Advanced Studio Management" },
            { id: 81372, name: "Induction Efficiency" },
            { id: 81373, name: "Advanced Induction Efficiency" },
            { id: 81374, name: "Peak Induction Acceleration" },
            { id: 81375, name: "Batch Sequencing" },
            { id: 81377, name: "Basic Induction" },
            { id: 81896, name: "Mutagenic Stabilization" },
            { id: 83094, name: "Capital Jump Portal Generation" },
            { id: 83464, name: "Capital Micro Jump Drive Operation" },
            { id: 84217, name: "Paragon Relations" },
            { id: 84218, name: "Paragon Partnership" },
            { id: 84220, name: "Executive Paragon Partnership" },
            { id: 85233, name: "Mercenary Den Management" },
            { id: 86260, name: "Breacher Pod Launcher Operation" },
            { id: 86261, name: "Breacher Pod Clone Efficacity" },
            { id: 86262, name: "Breacher Pod Clone Longevity" },
            { id: 86263, name: "Breacher Pod Projection" },
            { id: 86264, name: "Breacher Pod Rapid Firing" },
            { id: 88377, name: "Advanced Doomsday Operation" },
            { id: 92541, name: "Capital Disintegrator Specialization" },

        ]
    }
};

// Flattened array for search (use Types directly since MarketItems is defined later)
const AllMarketItems = Object.values(Types).flatMap(category => 
    category.items.map(item => ({
        ...item,
        category: category.name,
        icon: category.icon
    }))
);

// Popular items for quick access (subset of most traded)
const PopularItems = [
    { id: 44992, name: "30 Day Pilot's License Extension (PLEX)", category: "Trade Goods" },
    { id: 40520, name: "Large Skill Injector", category: "Trade Goods" },
    { id: 34, name: "Tritanium", category: "Materials" },
    { id: 35, name: "Pyerite", category: "Materials" },
    { id: 36, name: "Mexallon", category: "Materials" },
    { id: 37, name: "Isogen", category: "Materials" },
    { id: 38, name: "Nocxium", category: "Materials" },
    { id: 39, name: "Zydrine", category: "Materials" },
    { id: 40, name: "Megacyte", category: "Materials" },
    { id: 28668, name: "Nanite Repair Paste", category: "Ammunition" },
    { id: 587, name: "Rifter", category: "Frigates" },
    { id: 620, name: "Stabber", category: "Cruisers" },
    { id: 638, name: "Tempest", category: "Battleships" },
    { id: 24696, name: "Hurricane", category: "Battlecruisers" },
    { id: 16242, name: "Thrasher", category: "Destroyers" },
    { id: 210, name: "1MN Afterburner I", category: "Propulsion" },
    { id: 343, name: "1MN Microwarpdrive I", category: "Propulsion" },
    { id: 377, name: "Small Shield Extender I", category: "Shield Modules" },
    { id: 338, name: "Small Armor Repairer I", category: "Armor Modules" },
    { id: 384, name: "EM Shield Hardener I", category: "Shield Modules" },
    { id: 2048, name: "Damage Control I", category: "Armor Modules" },
];

// Regions data
const Regions = {
    0: { name: "All Regions (New Eden)", tradeHub: null },
    10000002: { name: "The Forge", tradeHub: "Jita IV - Moon 4 - Caldari Navy Assembly Plant" },
    10000043: { name: "Domain", tradeHub: "Amarr VIII (Oris) - Emperor Family Academy" },
    10000032: { name: "Sinq Laison", tradeHub: "Dodixie IX - Moon 20 - Federation Navy Assembly Plant" },
    10000030: { name: "Heimatar", tradeHub: "Rens VI - Moon 8 - Brutor Tribe Treasury" },
    10000042: { name: "Metropolis", tradeHub: "Hek VIII - Moon 12 - Boundless Creation Factory" }
};

// Conversion utilities for SDE compatibility
const MarketItems = Types; // Backward compatibility

// Convert old format to new SDE invTypes format
const invTypes = {};
AllMarketItems.forEach(item => {
    // Find group and category
    let groupID = null;
    let categoryID = null;
    
    // Try to find matching group
    for (const [gid, group] of Object.entries(Groups)) {
        if (group.name === item.category || item.category.includes(group.name)) {
            groupID = parseInt(gid);
            categoryID = group.categoryID;
            break;
        }
    }
    
    // Default mappings for categories not in Groups
    if (!categoryID) {
        switch(item.category) {
            case 'Materials': categoryID = 4; groupID = 18; break;
            case 'Frigates': categoryID = 6; groupID = 25; break;
            case 'Destroyers': categoryID = 6; groupID = 420; break;
            case 'Cruisers': categoryID = 6; groupID = 26; break;
            case 'Battlecruisers': categoryID = 6; groupID = 419; break;
            case 'Battleships': categoryID = 6; groupID = 27; break;
            case 'Industrials': categoryID = 6; groupID = 28; break;
            case 'Capital Ships': categoryID = 6; groupID = 485; break;
            case 'Turrets & Launchers': categoryID = 7; groupID = 53; break;
            case 'Shield Modules': categoryID = 7; groupID = 76; break;
            case 'Armor Modules': categoryID = 7; groupID = 57; break;
            case 'Ammunition & Charges': categoryID = 8; groupID = 85; break;
            case 'Trade Goods': categoryID = 39; groupID = 1033; break;
            case 'Drones': categoryID = 40; groupID = 97; break;
            case 'Implants & Boosters': categoryID = 20; groupID = 20; break;
            case 'Skillbooks': categoryID = 16; groupID = 150; break;
            case 'Blueprints': categoryID = 9; groupID = 9; break;
        }
    }
    
    invTypes[item.id] = {
        typeID: item.id,
        name: item.name,
        groupID: groupID,
        categoryID: categoryID,
        categoryName: item.category,
        published: true
    };
});

// Generate invCategories for SDE export
const invCategories = {};
for (const [id, cat] of Object.entries(Categories)) {
    invCategories[id] = {
        categoryID: parseInt(id),
        name: cat.name,
        published: true
    };
}

// Generate invGroups for SDE export
const invGroups = {};
for (const [id, group] of Object.entries(Groups)) {
    invGroups[id] = {
        groupID: parseInt(id),
        categoryID: group.categoryID,
        name: group.name,
        published: true
    };
}

// Export in multiple formats for compatibility
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { 
        // Original format (backward compatibility)
        MarketItems, 
        AllMarketItems, 
        PopularItems, 
        Regions,
        // Official SDE format
        Categories,
        Groups,
        Types,
        invCategories,
        invGroups,
        invTypes,
        // Utility functions
        getItemByTypeID: (typeID) => invTypes[typeID] || null,
        getItemsByGroup: (groupID) => Object.values(invTypes).filter(t => t.groupID === groupID),
        getItemsByCategory: (categoryID) => Object.values(invTypes).filter(t => t.categoryID === categoryID),
        searchItems: (query) => AllMarketItems.filter(i => i.name.toLowerCase().includes(query.toLowerCase()))
    };
}

